/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVendorsRouteImport } from './routes/_authenticated/vendors'
import { Route as AuthenticatedStudentsRouteImport } from './routes/_authenticated/students'
import { Route as AuthenticatedStaffRouteImport } from './routes/_authenticated/staff'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedInspectorsRouteImport } from './routes/_authenticated/inspectors'
import { Route as AuthenticatedGraphicsRouteImport } from './routes/_authenticated/graphics'
import { Route as AuthenticatedFormsRouteImport } from './routes/_authenticated/forms'
import { Route as AuthenticatedEventsRouteImport } from './routes/_authenticated/events'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunitiesRouteImport } from './routes/_authenticated/communities'
import { Route as AuthenticatedChatRouteImport } from './routes/_authenticated/chat'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedBugReportsRouteImport } from './routes/_authenticated/bug_reports'
import { Route as AuthenticatedStudentDetailRouteImport } from './routes/_authenticated/students.$id'
import { Route as AuthenticatedEventDetailRouteImport } from './routes/_authenticated/events.$id'
import { Route as FormsPTokenRouteImport } from './routes/forms.p.$token'
import { Route as AuthenticatedAdminWebhooksRouteImport } from './routes/_authenticated/admin.webhooks'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as ApiPublicFormsTokenRouteImport } from './routes/api/public/forms.$token'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVendorsRoute = AuthenticatedVendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentsRoute = AuthenticatedStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStaffRoute = AuthenticatedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInspectorsRoute = AuthenticatedInspectorsRouteImport.update({
  id: '/inspectors',
  path: '/inspectors',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGraphicsRoute = AuthenticatedGraphicsRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFormsRoute = AuthenticatedFormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEventsRoute = AuthenticatedEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChatRoute = AuthenticatedChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute = AuthenticatedNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBugReportsRoute = AuthenticatedBugReportsRouteImport.update({
  id: '/bug-reports',
  path: '/bug-reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentDetailRoute = AuthenticatedStudentDetailRouteImport.update({
  id: '/students/$id',
  path: '/students/$id',
  getParentRoute: () => AuthenticatedStudentsRoute,
} as any)
const AuthenticatedEventDetailRoute = AuthenticatedEventDetailRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => AuthenticatedEventsRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommunitiesRoute =
  AuthenticatedCommunitiesRouteImport.update({
    id: '/communities',
    path: '/communities',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const FormsPTokenRoute = FormsPTokenRouteImport.update({
  id: '/forms/p/$token',
  path: '/forms/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminWebhooksRoute =
  AuthenticatedAdminWebhooksRouteImport.update({
    id: '/admin/webhooks',
    path: '/admin/webhooks',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/admin/logs',
  path: '/admin/logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicFormsTokenRoute = ApiPublicFormsTokenRouteImport.update({
  id: '/api/public/forms/$token',
  path: '/api/public/forms/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/chat': typeof AuthenticatedChatRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/bug-reports': typeof AuthenticatedBugReportsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/graphics': typeof AuthenticatedGraphicsRoute
  '/inspectors': typeof AuthenticatedInspectorsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/students/$id': typeof AuthenticatedStudentDetailRoute
  '/events/$id': typeof AuthenticatedEventDetailRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/forms/p/$token': typeof FormsPTokenRoute
  '/api/public/forms/$token': typeof ApiPublicFormsTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/communities': typeof AuthenticatedCommunitiesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/chat': typeof AuthenticatedChatRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/bug-reports': typeof AuthenticatedBugReportsRoute
  '/events': typeof AuthenticatedEventsRoute
  '/forms': typeof AuthenticatedFormsRoute
  '/graphics': typeof AuthenticatedGraphicsRoute
  '/inspectors': typeof AuthenticatedInspectorsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/staff': typeof AuthenticatedStaffRoute
  '/students': typeof AuthenticatedStudentsRoute
  '/students/$id': typeof AuthenticatedStudentDetailRoute
  '/events/$id': typeof AuthenticatedEventDetailRoute
  '/vendors': typeof AuthenticatedVendorsRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/forms/p/$token': typeof FormsPTokenRoute
  '/api/public/forms/$token': typeof ApiPublicFormsTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/communities': typeof AuthenticatedCommunitiesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/events': typeof AuthenticatedEventsRoute
  '/_authenticated/forms': typeof AuthenticatedFormsRoute
  '/_authenticated/graphics': typeof AuthenticatedGraphicsRoute
  '/_authenticated/inspectors': typeof AuthenticatedInspectorsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/staff': typeof AuthenticatedStaffRoute
  '/_authenticated/students': typeof AuthenticatedStudentsRoute
  '/_authenticated/vendors': typeof AuthenticatedVendorsRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/webhooks': typeof AuthenticatedAdminWebhooksRoute
  '/forms/p/$token': typeof FormsPTokenRoute
  '/api/public/forms/$token': typeof ApiPublicFormsTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/communities'
    | '/dashboard'
    | '/chat'
    | '/notifications'
    | '/bug-reports'
    | '/events'
    | '/events/$id'
    | '/students'
    | '/students/$id'
    | '/forms'
    | '/graphics'
    | '/inspectors'
    | '/reports'
    | '/staff'
    | '/vendors'
    | '/admin/logs'
    | '/admin/users'
    | '/admin/webhooks'
    | '/forms/p/$token'
    | '/api/public/forms/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/communities'
    | '/dashboard'
    | '/chat'
    | '/notifications'
    | '/bug-reports'
    | '/events'
    | '/events/$id'
    | '/forms'
    | '/graphics'
    | '/inspectors'
    | '/reports'
    | '/staff'
    | '/students'
    | '/students/$id'
    | '/vendors'
    | '/admin/logs'
    | '/admin/users'
    | '/admin/webhooks'
    | '/forms/p/$token'
    | '/api/public/forms/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/communities'
    | '/_authenticated/dashboard'
    | '/_authenticated/chat'
    | '/_authenticated/notifications'
    | '/_authenticated/bug-reports'
    | '/_authenticated/events'
    | '/_authenticated/events/$id'
    | '/_authenticated/forms'
    | '/_authenticated/graphics'
    | '/_authenticated/inspectors'
    | '/_authenticated/reports'
    | '/_authenticated/staff'
    | '/_authenticated/students'
    | '/_authenticated/students/$id'
    | '/_authenticated/vendors'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/webhooks'
    | '/forms/p/$token'
    | '/api/public/forms/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  FormsPTokenRoute: typeof FormsPTokenRoute
  ApiPublicFormsTokenRoute: typeof ApiPublicFormsTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vendors': {
      id: '/_authenticated/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof AuthenticatedVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/students': {
      id: '/_authenticated/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AuthenticatedStudentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/staff': {
      id: '/_authenticated/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthenticatedStaffRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inspectors': {
      id: '/_authenticated/inspectors'
      path: '/inspectors'
      fullPath: '/inspectors'
      preLoaderRoute: typeof AuthenticatedInspectorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/graphics': {
      id: '/_authenticated/graphics'
      path: '/graphics'
      fullPath: '/graphics'
      preLoaderRoute: typeof AuthenticatedGraphicsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forms': {
      id: '/_authenticated/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof AuthenticatedFormsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/events': {
      id: '/_authenticated/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof AuthenticatedEventsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/communities': {
      id: '/_authenticated/communities'
      path: '/communities'
      fullPath: '/communities'
      preLoaderRoute: typeof AuthenticatedCommunitiesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/forms/p/$token': {
      id: '/forms/p/$token'
      path: '/forms/p/$token'
      fullPath: '/forms/p/$token'
      preLoaderRoute: typeof FormsPTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/webhooks': {
      id: '/_authenticated/admin/webhooks'
      path: '/admin/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AuthenticatedAdminWebhooksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/admin/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/forms/$token': {
      id: '/api/public/forms/$token'
      path: '/api/public/forms/$token'
      fullPath: '/api/public/forms/$token'
      preLoaderRoute: typeof ApiPublicFormsTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCommunitiesRoute: typeof AuthenticatedCommunitiesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEventsRoute: typeof AuthenticatedEventsRoute
  AuthenticatedFormsRoute: typeof AuthenticatedFormsRoute
  AuthenticatedGraphicsRoute: typeof AuthenticatedGraphicsRoute
  AuthenticatedInspectorsRoute: typeof AuthenticatedInspectorsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedStaffRoute: typeof AuthenticatedStaffRoute
  AuthenticatedStudentsRoute: typeof AuthenticatedStudentsRoute
  AuthenticatedVendorsRoute: typeof AuthenticatedVendorsRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWebhooksRoute: typeof AuthenticatedAdminWebhooksRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCommunitiesRoute: AuthenticatedCommunitiesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEventsRoute: AuthenticatedEventsRoute,
  AuthenticatedFormsRoute: AuthenticatedFormsRoute,
  AuthenticatedGraphicsRoute: AuthenticatedGraphicsRoute,
  AuthenticatedInspectorsRoute: AuthenticatedInspectorsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedStaffRoute: AuthenticatedStaffRoute,
  AuthenticatedStudentsRoute: AuthenticatedStudentsRoute,
  AuthenticatedVendorsRoute: AuthenticatedVendorsRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWebhooksRoute: AuthenticatedAdminWebhooksRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  FormsPTokenRoute: FormsPTokenRoute,
  ApiPublicFormsTokenRoute: ApiPublicFormsTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
